### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bruno12mota**

### CODE REVIEW

**Comment by magalhas** [comment]
Unit tests are failing due to this change.

**Comment by magalhas** [comment]
Please don't PR the built file (/dist) as well.

**Comment by bruno12mota** [comment]
Tests passing now, why wouldn't I PR the built files? Or you gitignore them so they don't get into the repo or you accept them as part of the PR

**Comment by magalhas** [comment]
The build is executed and commited when there's a release.

Cumprimentos,
José Magalhães

**Comment by bruno12mota** [comment]
The build should then replace my build right?

**Pull request merged**
