### PR TITLE
Demo for react-router and backbone-react-component

### PR DESCRIPTION
**Pull request by ieugen**
This is also an example on how to use React Router, React and Backbone React Component. 

It would be nice to have it merged.

### CODE REVIEW

**Comment by magalhas** [comment]
Sweet. I'll take a look during the weekend :+1: Thank you

**Comment by ieugen** [comment]
As I've said, React has some life cycle methods that we can leverage to bind/unbind Backbone React Component (BRC). The mixin cold do this automatically, but it would be nice to use BRC without mixin, by means of life cycel methods. 

For example, we could do the binding in

**Comment by magalhas** [comment]
@ieugen why have you closed this issue? Regarding the non mixin method, it's a must for ES6 classes #67

**Comment by ieugen** [comment]
Sorry, my "big fingers" slipped.

**Comment by magalhas** [comment]
@ieugen does the bug reported in #65 occur in here or should I change the routes to make it happen ? As far as I can tell the routes in the example are query free, no?

**Comment by ieugen** [comment]
Run the app with broccoli serve. The links send query params. Override
method is not taken into account on query change.

Joi, 2 apr. 2015, 04:54, José Magalhães <notifications@github.com> a scris:

**Comment by magalhas** [comment]
Probably we're missing one lifecycle hook :+1:

**Comment by ieugen** [comment]
Yes, my thought exactly. By the way, have you given a thought on bindings
without the use of a mixin?

2015-04-02 18:15 GMT+03:00 José Magalhães <notifications@github.com>:

> Probably we're missing one lifecycle hook [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magalhas/backbone-react-component/pull/68#issuecomment-88941182>
> .
>



-- 
Ioan Eugen Stan
0720 898 747

**Comment by magalhas** [comment]
@ieugen yes I'll link you on the other issue when I make a comment with my thoughts so that you can contribute with your ideas.

**Pull request merged**
