### PR TITLE
FIX HTML5 validator errors in blog example

### PR DESCRIPTION
**Pull request by lzrski**
There were several errors in public/index.html file.

### CODE REVIEW

**Comment by magalhas** [comment]
The examples are kind of broken in the latest version of the lib, but I'm going to accept your PR. Thank you for noticing :+1:

**Comment by lzrski** [comment]
Thanks.

Sorry to hear that. I'm new to React and I was hoping to learn basics from your examples.

Is the readme up to date? Or is there some list of API changes, so maybe I could fix the examples and learn by doing that? Where should I start?

**Comment by magalhas** [comment]
There were some changes (you can check the changelog on the releases section) and I've not updated the examples yet although the README is up to date. Feel free to run and fix them if you find the time for it :+1:

**Comment by lzrski** [comment]
Can't promise anything :) Thx.

**Pull request merged**
